version: '3'

services:
  mailhog:
     image: mailhog/mailhog
     ports: 
       - 1025:1025 # smtp server
       - 8025:8025 # web ui

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # Message port
      - "15672:15672" # Web UI

  buyscoutapi:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    ports:
      - 5001:5001
      #- 6001:5001
      - 6000:80
      - 6001:80
    volumes:
      - C:\dev\github\swizkon\buyscout\src\dotnet:/app
    working_dir: /app/BuyScout.API
    command: dotnet watch run
    depends_on:
      - mailhog
      - rabbitmq