version: '3'

services:
  mailhog:
     image: mailhog/mailhog
     ports: 
       - 1025:1025 # smtp server
       - 8025:8025 # web ui

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # Message port
      - "15672:15672" # Web UI

    # volumes:
    #   - 'rabbitmq_data:/data'

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb:/data/db

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock